#!/usr/bin/env bash

test_add_with_no_link() {
    touch ${sandbox}/test_file
    echo "test_file" > ${sandbox}/test_file

    ./cm add ${sandbox}/test_file ${sandbox}/foo
    
    [[  -e ${sandbox}/foo/test_file && \
        -e ${sandbox}/foo/formula && \
        ! -e ${sandbox}/foo/links \
    ]]
}

test_add_file_that_does_not_exist() {
    ./cm add ${sandbox}/test_file ${sandbox}/foo
    [[ $? -eq 1 ]]
}

test_add_missing_args() {
    ! ./cm add &&
    ! ./cm add ${sandbox}/test_file
}

main() {
    run test_add_with_no_link
    run test_add_file_that_does_not_exist 
    run test_add_missing_args
}

$@
