#!/usr/bin/env bash

test_apply_simple() {
    touch "$sandbox/test_file"

    mkdir "$sandbox/foo"
    touch "$sandbox/foo/links"
    touch "$sandbox/foo/formula"
    
    local source
    source="$(norm_path "$sandbox/test_file")"
    local target
    target="$(norm_path "$sandbox/foo/test_file")"

    echo "$source -> $target" > "$sandbox/foo/links"

    ./cm apply --rm "$sandbox/foo"

    [[ -L "$sandbox/test_file" ]]
}

main() {
    run test_apply_simple
}

"$@"
