#!/usr/bin/env bash

run() {
    local cmd=$@
    
    # make sandbox
    mkdir -p "$cmd.sandbox"
    export sandbox="$cmd.sandbox"
    
    # run test and report result
    $cmd > "$cmd.log" 2>&1
    if [[ $? -eq 0 ]]; then
        echo "PASS $cmd"
        rm "$cmd.log"
        rm -rf ${sandbox}
    else
        echo "FAIL $cmd"
        echo ">>>>>>>>"
        echo "Output:"
        echo ""
        cat "$cmd.log"
        echo ""
        echo "Note: You can view this log at '$cmd.log'"
        echo "Note: You can view the sandbox for this run at '$cmd.sandbox'"
        echo "<<<<<<<<"
    fi
}

main() {
    source ./env
    source ./util
    export -f run

    rm -rf *.sandbox
    rm -rf *.log
    
    ./test/add main
}

main
