#!/usr/bin/env bash

run() {
    local cmd=$*
    
    # make sandbox
    mkdir -p "$cmd.sandbox"
    export sandbox="$cmd.sandbox"
    
    # run test and report result
    if $cmd > "$cmd.log" 2>&1; then
        echo "PASS $cmd"
        rm "$cmd.log"
        rm -rf "${sandbox}"
    else
        echo "FAIL $cmd"
        echo ">>>>>>>>"
        echo "Output:"
        echo ""
        cat "$cmd.log"
        echo ""
        echo "Note: You can view this log at '$cmd.log'"
        echo "Note: You can view the sandbox for this run at '$cmd.sandbox'"
        echo "<<<<<<<<"
    fi
}

main() {
    local test_base
    test_base="$(dirname $0)"
    local base
    base="$(dirname $test_base)"
    local cmd="$1"

    source "$base/env"
    source "$base/util"
    export -f run

    rm -rf "$base/*.sandbox"
    rm -rf "$base/*.log"
    
    "$test_base/$cmd" main
}

main "$@"
