#!/usr/bin/env bash

test_install_empty() {
    cat << EOF > "$sandbox/expected.log"
[info] DRY RUN
[info] Processing '$sandbox'
[done]
EOF

    ./cm install --dry-run -v "$sandbox" > "$sandbox/actual.log" 2>&1
    
    diff -w "$sandbox/actual.log" "$sandbox/expected.log"
}

test_install_no_formula() {
    mkdir "$sandbox/foo"
    touch "$sandbox/test_file1"
    touch "$sandbox/foo/test_file2"

    cat << EOF > "$sandbox/expected.log" 
[info] DRY RUN
[info] Processing '$sandbox/foo'
[done]
[info] Processing '$sandbox'
[done]
EOF

    ./cm install --dry-run -v "$sandbox" > "$sandbox/actual.log" 2>&1

    diff -w "$sandbox/actual.log" "$sandbox/expected.log"
}

test_install_no_formula_nested() {
    mkdir -p "$sandbox/foo/a"
    mkdir -p "$sandbox/foo/b"
    mkdir -p "$sandbox/bar"
    mkdir -p "$sandbox/baz/c/d"

    cat << EOF > "$sandbox/expected.log"
[info] DRY RUN
[info] Processing '$sandbox/bar'
[done]
[info] Processing '$sandbox/baz/c/d'
[done]
[info] Processing '$sandbox/baz/c'
[done]
[info] Processing '$sandbox/baz'
[done]
[info] Processing '$sandbox/foo/a'
[done]
[info] Processing '$sandbox/foo/b'
[done]
[info] Processing '$sandbox/foo'
[done]
[info] Processing '$sandbox'
[done]
EOF
    
    ./cm install --dry-run -v "$sandbox" > "$sandbox/actual.log" 2>&1

    diff -w "$sandbox/actual.log" "$sandbox/expected.log"
}

test_install_formula_nested() {
    ./cm add -f "$sandbox/foo"
    ./cm add -f "$sandbox/foo/a"
    ./cm add -f "$sandbox/foo/b"
    ./cm add -f "$sandbox/bar"
    ./cm add -f "$sandbox/baz"
    ./cm add -f "$sandbox/baz/c"
    ./cm add -f "$sandbox/baz/c/d"

    cat << EOF > "$sandbox/expected.log"
[info] Processing '$sandbox/bar'
[info] FIXME: installing
[info] Installed '$sandbox/bar/formula'
[info] FIXME: configuring
[info] Configured '$sandbox/bar/formula'
[info] '$sandbox/bar/links' does not exist; skipping apply links
[done]
[info] Processing '$sandbox/baz/c/d'
[info] FIXME: installing
[info] Installed '$sandbox/baz/c/d/formula'
[info] FIXME: configuring
[info] Configured '$sandbox/baz/c/d/formula'
[info] '$sandbox/baz/c/d/links' does not exist; skipping apply links
[done]
[info] Processing '$sandbox/baz/c'
[info] FIXME: installing
[info] Installed '$sandbox/baz/c/formula'
[info] FIXME: configuring
[info] Configured '$sandbox/baz/c/formula'
[info] '$sandbox/baz/c/links' does not exist; skipping apply links
[done]
[info] Processing '$sandbox/baz'
[info] FIXME: installing
[info] Installed '$sandbox/baz/formula'
[info] FIXME: configuring
[info] Configured '$sandbox/baz/formula'
[info] '$sandbox/baz/links' does not exist; skipping apply links
[done]
[info] Processing '$sandbox/foo/a'
[info] FIXME: installing
[info] Installed '$sandbox/foo/a/formula'
[info] FIXME: configuring
[info] Configured '$sandbox/foo/a/formula'
[info] '$sandbox/foo/a/links' does not exist; skipping apply links
[done]
[info] Processing '$sandbox/foo/b'
[info] FIXME: installing
[info] Installed '$sandbox/foo/b/formula'
[info] FIXME: configuring
[info] Configured '$sandbox/foo/b/formula'
[info] '$sandbox/foo/b/links' does not exist; skipping apply links
[done]
[info] Processing '$sandbox/foo'
[info] FIXME: installing
[info] Installed '$sandbox/foo/formula'
[info] FIXME: configuring
[info] Configured '$sandbox/foo/formula'
[info] '$sandbox/foo/links' does not exist; skipping apply links
[done]
[info] Processing '$sandbox'
[done]
EOF
    
    ./cm install -v "$sandbox" > "$sandbox/actual.log" 2>&1

    diff -w "$sandbox/actual.log" "$sandbox/expected.log"
}

main() {
    run test_install_empty
    run test_install_no_formula
    run test_install_no_formula_nested
    run test_install_formula_nested
}

"$@"
