#!/usr/bin/env bash

set -e
source ./env

if [[ $# -eq 0 ]]; then
  help_text
fi

cmd="$1"
if [[ ! -e "cmd/$cmd" ]]; then
    warn "The command $cmd doesn't exist. See help text below for a list of supported commands"
    cmd/help "main" "index"
else
    shift
    cmd/$cmd "main" $@
fi
