#!/usr/bin/env bash

is_formula() {
    local dir="$1"
    [[ -d $dir && -e $dir/formula ]]
}

norm_path() {
    local path="$1"
    echo "$(cd "$(dirname "$path")" || exit; pwd)/$(basename "$path")"
}

assert_num_args_at_least() {
    local expected="$1"
    local actual="$2"
    if [[ $actual -lt $expected ]]; then
        error "Insufficient number of args. Expected $expected args."
    fi
}

invalid_opt_error() {
  local opt="$1"
  error "Invalid option '$opt'"
}

export -f is_formula
export -f norm_path
export -f assert_num_args_at_least
export -f invalid_opt_error
