#!/usr/bin/env bash

create_formula() {
    formula="$1"
    
    if [[ -e "$formula/formula" ]]; then
      error "formula $formula already exists"
    fi

    mkdir -p "$formula"
    touch "$formula/formula"
    cp ./templates/formula_template "$formula/formula"
    info "created formula $formula_dir"
}

prompt_to_save_link() {
    if [[ ! -e "./links" ]]; then
      touch "./links"
    fi
    repo_relative_path="$1"
    echo "FIXME: path/to/symlink -> $repo_relative_path" >> "./links"
    vim "./links"
}

add_item_to_formula() {
    item="$1"
    formula="$2"
    flag_link="$3"
    
    info "adding $item to $formula"

    if [[ ! -e "$formula/formula" ]]; then
      create_formula "$formula"
    fi
    
    cp -R "$item" "$formula"

    if [[ "$flag_link" ]]; then
      info "creating a symlink"
      ln -svf "$formula/$(basename $item)" "$item"
      prompt_to_save_link "$formula/$(basename $item)"
    fi
      
    success
}


main() {
    local flag_formula
    local flag_link

    for arg in "$@"; do
      case $1 in
        -f|--formula)
          shift
          flag_formula=true
          ;;
        -l|--link)
          shift
          flag_link=true
          ;;
        *)
          break
          ;;
      esac
    done

    if [[ $flag_formula && ! $flag_link ]]; then
      create_formula "$1"
    else
      add_item_to_formula "$1" "$2" $flag_link
    fi
}

$@
