#!/usr/bin/env bash

set -e

create_formula() {
    formula="$1"
    
    if [[ -e "$formula/formula" ]]; then
      error "formula $formula already exists"
    fi

    mkdir -p "$formula"
    touch "$formula/formula"
    cp ./templates/formula_template "$formula/formula"
    chmod +x "$formula/formula"
    info "Created formula $formula"
}

prompt_to_save_link() {
    local formula="$1"
    local item
    item=$(basename "$2")
    local links_path=$formula/links

    if [[ ! -e $links_path ]]; then
      touch "$links_path"
    fi
    echo "FIXME: path/to/symlink -> $formula/$item" >> "$links_path"
    vim "$links_path"
}

save_link_to_file() {
    local source="$1"
    local target="$2"
    local file="$3"
    
    local line="~${source/$HOME} -> $target"
    info "added '$line' to '$file'"
    echo "$line" >> "$file"
}

add_item_to_formula() {
    item=$(norm_path "$1")
    formula="$2"
    flag_link="$3"

    if [[ ! -e $item ]]; then
        error "'$item' does not exist" 
    fi
    
    info "adding $item to $formula"

    if [[ ! -e "$formula/formula" ]]; then
      create_formula "$formula"
    fi
    
    cp -R "$item" "$formula"

    if [[ "$flag_link" ]]; then
      info "creating a symlink"
      if [[ -d "$item" ]]; then
          rm -rf "$item"
      fi
      ln -svf "$formula/$(basename "$item")" "$item"

      # prompt_to_save_link "$formula" "$item"
      save_link_to_file "$item" "$formula/$(basename "$item")" "$formula/links"
    fi
}


main() {
    local flag_formula
    local flag_link

    while [[ $# -ne 0 ]]; do
        case $1 in
            -f|--formula)
            shift
            flag_formula=true
            ;;
            -l|--link)
            shift
            flag_link=true
            ;;
            *)
            break
            ;;
        esac
    done

    if [[ $flag_formula && ! $flag_link ]]; then
        if [[ $# -lt 1 ]]; then
            error "Insufficient number of args"
        fi
        create_formula "$1"
    else
        if [[ $# -lt 2 ]]; then
            error "Insufficient number of args"
        fi
        add_item_to_formula "$1" "$2" $flag_link
    fi
}

"$@"
