#!/usr/bin/env bash

set -e

create_formula() {
    formula="$1"
    
    if [[ -e "$formula/formula" ]]; then
      error "formula $formula already exists"
    fi

    mkdir -p "$formula"
    touch "$formula/formula"
    cp "$base/templates/formula_template" "$formula/formula"
    chmod +x "$formula/formula"
    info "Created formula $formula"
}

save_link_to_file() {
    local source="$1"
    local target="$2"
    local file="$3"
    
    local line="~${source/$HOME} -> $target"
    info "Added '$line' to '$file'"
    echo "$line" >> "$file"
}

add_item_to_formula() {
    local flag_link="$1"
    local args=("$@")
    local formula=${args[${#args[@]}-1]}
    
    for i in $(seq 1 $((${#args[@]}-2))); do
        local item=$(norm_path ${args[$i]})

        if [[ ! -e $item ]]; then
            error "'$item' does not exist" 
        fi
        
        if [[ ! -e "$formula/formula" ]]; then
            create_formula "$formula"
        fi
        
        if [[ -d "$item" ]]; then
            cp -r "$item"/* "$formula"
        else
            cp "$item" "$formula"
        fi

        if [[ "$flag_link" = true ]]; then
            local source 
            if [[ -d "$item" ]]; then
                source="$formula"
                rm -rf "$item"
            else
                source="$formula/$(basename "$item")"
            fi
                        
            out=$(ln -svf "$(norm_path $source)" "$item")
            info "Created symlink: $out"
            save_link_to_file "$item" "$source" "$formula/links"
        fi

        info "Added $item to $formula"
    done
}


main() {
    local flag_formula=false
    local flag_link=false

    while [[ $# -ne 0 ]]; do
        case $1 in
            -f|--formula)
            shift
            flag_formula=true
            ;;
            -l|--link)
            shift
            flag_link=true
            ;;
            *)
            break
            ;;
        esac
    done

    if [[ $flag_formula = true && $flag_link = false ]]; then
        if [[ $# -lt 1 ]]; then
            error "Insufficient number of args"
        fi
        create_formula "$1"
    else
        if [[ $# -lt 2 ]]; then
            error "Insufficient number of args"
        fi
        add_item_to_formula $flag_link "$@"
    fi
}

"$@"
