#!/usr/bin/env bash

set -e

apply() {
    local copy="$1"
    local force_remove="$2"
    local line="$3"
    local target 
    local source

    target=$(norm_path $(echo "$line" | awk '{print $1}'))
    source=$(norm_path $(echo "$line" | awk '{print $3}'))

    if [[ -e "$target" ]]; then
        if [[ $force_remove = true ]]; then
            rm -rf "$target"
        else
            error "'$target' already exists! Pass the '--rm' option to forcefully remove it"
        fi
    fi
    if [[ $copy = true ]]; then
        cp -R "$source" "$target"
        info "Created a copy of '$source' at '$target'"
    else
        out=$(ln -svf "$source" "$target")
        info "Created symbolic link: $out"
    fi
}

apply_links_from_file() {
    local dry_run="$1"
    local copy="$2"
    local force_remove="$3"
    local links_file_path="$4"

    if [[ $dry_run = true ]]; then
        cat "$links_file_path"
    else
        cat "$links_file_path"
        while read -r line; do
            apply "$copy" "$force_remove" "$line" 
        done < "$links_file_path"
    fi
}

main() {
    local copy=false
    local dry_run=false
    local force_remove=false

    while [[ $# -ne 0 ]]; do
        case "$1" in
            -c|--copy)
                shift
                copy=true
                ;;
            --dry-run)
                shift
                dry_run=true
                ;;
            --rm)
                shift
                force_remove=true
                ;;
            -*)
                invalid_opt_error $1
                ;;
            *)
                break
        esac
    done

    for formula in "$@"; do
        if ! is_formula "$formula"; then
            error "'$formula' is not a formula"
        fi

        links_file="$formula/links"
        if [[ -e "$links_file" ]]; then
            apply_links_from_file "$dry_run" "$copy" "$force_remove" "$links_file"
        else
            info "No 'links' file found for $formula; skipping"
        fi
    done
}

"$@"
