#!/usr/bin/env bash

main() {
    local cmd="$1"

    help_file="$base/help/$cmd"    
    if [[ ! -e "$help_file" ]]; then
        error "The command $1 does not exist"
    fi
    cat "$help_file"
}

"$@"
