#!/usr/bin/env bash

install_formula() {
    local formula="$1"
    local dry_run="$2"
    
    dirs=$(find "$formula" -type d -depth 1)

    for dir in $dirs; do
        install_formula "$dir" "$dry_run"
    done


    info "Processing '$formula'"

    if [[ -e "$formula/formula" ]]; then
        if [[ $dry_run ]]; then
            echo "$formula/formula"
        else
            info "Installing $formula/formula"
            "$formula/formula" install
            info "Configuring $formula/formula"
            "$formula/formula" configure

            if [[ -f "$dir/links" ]]; then
                apply_links_from_file "$dir/links" "$dry_run"
            else
                info "'$dir/links' does not exist; skipping apply links"
            fi
        fi
    fi
    
    checkpoint
}

main() {
    local dry_run

    # process flags
    for arg in "$@"; do
        case $arg in
            --dry-run)
                shift
                dry_run=true
                info "DRY RUN"
                break
                ;;
            -*)
                error "Invalid flag: $arg"
                ;;
        esac
    done
    
    if [[ $# -eq 0 ]]; then
        install_formula . $dry_run
    else
        for arg in "$@"; do
            install_formula "$arg" $dry_run
        done
    fi
    
    success
}

"$@"
