#!/usr/bin/env bash

set -e

install_formula() {
    local formula="$1"
    local dry_run="$2"
    local verbose="$3"
    local dirs 
    dirs=$(find -s "$formula" -type d -depth 1)
    
    for dir in $dirs; do
        install_formula "$dir" "$dry_run" "$verbose"
    done

    if [[ $verbose = true ]]; then
        info "Processing '$formula'"
    fi
    
    if [[ -e "$formula/formula" ]]; then
        if [[ $dry_run = true ]]; then
            echo "$formula/formula"
        else
            "$formula/formula" install
            info "Installed '$formula/formula'"
            "$formula/formula" configure
            info "Configured '$formula/formula'"
        fi
    fi
    
    if [[ $verbose = true ]]; then
        checkpoint
    fi
}

main() {
    local dry_run=false
    local verbose=false

    # process flags
    for arg in "$@"; do
        case $arg in
            --dry-run)
                shift
                dry_run=true
                info "DRY RUN"
                ;;
            -v|--verbose)
                shift
                verbose=true
                ;; 
            -*)
                error "Invalid flag: $arg"
                ;;
            *)
                break
                ;;
        esac
    done

    if [[ $# -eq 0 ]]; then
        install_formula . $dry_run $verbose
    else
        for arg in "$@"; do
            install_formula "$arg" $dry_run $verbose
        done
    fi
}

"$@"
